#!/usr/bin/env node
'use strict';
// Local conditional forecasts; browser rendering and device performance are checked separately.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const extract=name=>{const text=html.split('// '+name+'_BEGIN')[1];assert.ok(text,'Missing shipped section '+name);return '//'+text.split('// '+name+'_END')[0];};
const api=vm.runInNewContext(['SYNC_MODEL','REMOTE_MODEL','GALAXY_MODEL','GHOST_MODEL','STAR_MODEL','ORBIT_MODEL','GALAXY_FIELD','AGENTIC_MODEL'].map(extract).join('\n')+'\n({SyncTest,RemoteTest,OrbitRemoteTest,GalaxyRemoteTest,StarField,OrbitalField,GalaxyField,cloneAgentWorld,ForecastRollout,AgenticWorld,agentDeepCopy,agentRoles,agentScout,agentGraph,agentEquivalent,AGENTIC_LIMITS,parseChallenge,challengeURL,GhostRecorder,ghostURL,parseGhost})',{URL,URLSearchParams});
const seed='A7F291C8',geometry={W:390,H:844,cx:195,cy:365.4,R:99.45,top:146,bottom:557};
let checks=0;function ok(value,label){assert.ok(value,label);checks++;console.log('PASS '+label);}
const json=value=>JSON.stringify(value),round=n=>Math.round(n*1e7)/1e7;
function world({rules='R3',time=10,level=0,otherSeed=seed}={}){const Field=rules==='R3'?api.GalaxyField:rules==='R2'?api.OrbitalField:api.StarField,Game=rules==='R3'?api.GalaxyRemoteTest:rules==='R2'?api.OrbitRemoteTest:api.RemoteTest,field=new Field(otherSeed),game=new Game(otherSeed);game.start();game.advance(time);if(rules==='R3'){game.growth=[0,18,45,85,135][level];field.setLevel(level);}field.update(game.elapsed,geometry,()=>{});return{field,game,geometry:{...geometry},rules};}
function finish(rollout,budget=8){let calls=0;while(!rollout.done){rollout.step(budget);if(++calls>2000)throw Error('Forecast exceeded bounded completion');}return rollout.result();}
function readyAgent(w,plan={}){const a=new api.AgenticWorld();a.begin(w.field,w.game,w.geometry,plan);let calls=0;while(!a.step(8)){if(++calls>2000)throw Error('Agent exceeded bounded completion');}return a;}
function target(w){return api.agentScout(w.field,w.geometry)[0]?.id;}
function armed(w,count=3){for(const star of w.field.stars.filter(s=>s.alive).slice(0,count))star.state='ARMED';w.game.timeLockLeft=w.game.driveLeft=5;return w;}
// An independent direct execution of the production physics, not the forecasting class.
function actual(w,plan,{dt=1/60,horizon=1.5}={}){const {field:f,game:g,geometry:geo}=w,chainId=f.chainId+1,out={count:0,mass:0,growth:0,timeBonus:0,ids:[],records:[]};const callback=(star,count,p,from,group)=>{if(!g.starBurst(count))return;const growthBefore=g.growth||0,timeBefore=g.timeBonus||0;if(g.absorb){g.absorb(star,count,group);f.setLevel(g.level);}if(group?.id!==chainId)return;out.count=Math.max(out.count,count);out.mass+=star.mass||1;out.growth+=(g.growth||0)-growthBefore;out.timeBonus+=(g.timeBonus||0)-timeBefore;out.ids.push(star.id);out.records.push({id:star.id,x:round(p.x),y:round(p.y),time:round(g.elapsed),count});};
 if(plan.kind==='tap'){const s=f.stars.find(s=>s.id===plan.targetId),p=f.point(s,geo);f.trigger(p.x,p.y,g.elapsed,geo,callback);}else if(plan.kind==='burst'){if(g.coreBurst(1.1))f.coreBurst(g.elapsed,geo,callback);}else{g.timeLockLeft=g.driveLeft=0;g.timeLockEnded=false;g.timeRestartAt=g.elapsed;if(plan.targetId!==null){const s=f.stars.find(s=>s.id===plan.targetId);if(s){const p=f.point(s,geo);f.arm(p.x,p.y,geo);}}g.restartArmed=f.stars.filter(s=>s.alive&&s.state==='ARMED').length;f.restart(g.elapsed,geo,callback);}
 let elapsed=0;while(elapsed<horizon-1e-9&&g.state==='playing'){const d=Math.min(dt,horizon-elapsed);g.advance(d);elapsed+=d;if(g.state==='playing')f.update(g.elapsed,geo,callback);}return out;}
function trace(result){return result.records.map(r=>({id:r.id,x:round(r.x),y:round(r.y),time:round(r.time),count:r.count}));}
function matchesForecast(r,a){return r.count===a.count&&Math.abs(r.mass-a.mass)<1e-7&&Math.abs(r.growth-a.growth)<1e-7&&Math.abs(r.timeBonus-a.timeBonus)<1e-7&&json(r.ids)===json(a.ids)&&json(trace(r))===json(a.records);}
for(const rules of ['R1','R2','R3']){
 const w=world({rules}),before=json(w),clone=api.cloneAgentWorld(w.field,w.game,w.geometry);
 ok(clone.rules===rules&&clone.snapshotTime===w.game.elapsed,rules+' snapshot retains exact rules and world time');
 ok(clone.field!==w.field&&clone.game!==w.game&&clone.geometry!==w.geometry,rules+' snapshot owns isolated field, game and geometry');
 clone.field.stars[0].state='DESTROYED';clone.game.energy=99;clone.geometry.R=20;ok(json(w)===before,rules+' edits to a clone cannot mutate the live world');
 const a=world({rules}),b=api.cloneAgentWorld(a.field,a.game,a.geometry);a.field.stars.splice(0,2);b.field.stars.splice(0,2);if(rules==='R1'){a.field.spawn(1,10.1);b.field.spawn(1,10.1);}else{a.field.spawn(10.1);b.field.spawn(10.1);}ok(json(a.field.stars)===json(b.field.stars),rules+' cloned PRNG reproduces the next actual spawn');
 const direct=world({rules}),plan={kind:'tap',targetId:target(direct)},predicted=finish(new api.ForecastRollout(direct.field,direct.game,direct.geometry,plan)),observed=actual(world({rules}),plan);
 ok(predicted.valid&&matchesForecast(predicted,observed),rules+' one-and-a-half-second tap forecast equals direct physics at the same cadence');
 const unchanged=world({rules}),state=json(unchanged);finish(new api.ForecastRollout(unchanged.field,unchanged.game,unchanged.geometry,{kind:'tap',targetId:target(unchanged)}));ok(json(unchanged)===state,rules+' complete forecasting leaves scoring, signal schedule and live stars unchanged');
 const agents=readyAgent(unchanged,{kind:'tap',mode:'challenge'});ok(json(unchanged)===state&&agents.best&&agents.evaluated<=4,rules+' completed agent tools leave the real Challenge world unchanged');
}
let w=world(),clone=api.cloneAgentWorld(w.field,w.game,w.geometry);const group={id:1,count:2};w.field.waves=[{chain:group,from:{x:1,y:2}},{chain:group,from:{x:3,y:4}}];clone=api.cloneAgentWorld(w.field,w.game,w.geometry);ok(clone.field.waves[0].chain===clone.field.waves[1].chain&&clone.field.waves[0].chain!==group,'Clone preserves shared chain-group identity without sharing live state');clone.field.waves[0].chain.count=7;ok(group.count===2&&clone.field.waves[1].chain.count===7,'Clone-local chain increments reach its sibling waves only');
const shared={value:2},collection={map:new Map([['entry',shared]]),set:new Set([shared]),shared};collection.self=collection;const collectionCopy=api.agentDeepCopy(collection);ok(collectionCopy.self===collectionCopy&&collectionCopy.shared===collectionCopy.map.get('entry')&&collectionCopy.set.has(collectionCopy.shared),'Deep copies preserve cycles and Map/Set shared aliases');collectionCopy.shared.value=9;ok(shared.value===2,'Copied collections never retain a live mutable entry');
w=world();const same=world(),different=world({otherSeed:'91C8A7F2'}),p={kind:'tap',targetId:target(w)},r1=finish(new api.ForecastRollout(w.field,w.game,w.geometry,p)),r2=finish(new api.ForecastRollout(same.field,same.game,same.geometry,p));ok(json(r1)===json(r2),'Same seed, snapshot and action produce identical forecast traces');ok(json(finish(new api.ForecastRollout(different.field,different.game,different.geometry,{kind:'tap',targetId:target(different)})))!==json(r1),'Different seed produces a different physical projection');
for(const kind of ['burst','restart']){const projected=kind==='restart'?armed(world()):world(),plan={kind,targetId:kind==='restart'?projected.field.stars.find(s=>s.state!=='ARMED').id:null,locked:kind==='restart'},copy=kind==='restart'?armed(world()):world(),before=json(projected),result=finish(new api.ForecastRollout(projected.field,projected.game,projected.geometry,plan));ok(result.valid&&matchesForecast(result,actual(copy,plan)),kind+' forecast follows the real existing power and shared chain');ok(json(projected)===before,kind+' tool cannot spend a live burst cell or drive activation');ok(result.tool===(kind==='burst'?'BURST SOLVER':'PHASE ANCHOR'),kind+' publishes the corresponding distinct tool capability');}
w=world();w.game.coreBursts=0;let invalid=finish(new api.ForecastRollout(w.field,w.game,w.geometry,{kind:'burst'}));ok(!invalid.valid&&invalid.reason==='burst-unavailable','BURST SOLVER refuses an exhausted CORE BURST');
const voidWorld=world({time:0}),voidStart=voidWorld.game.events.find(e=>e.kind==='VOID').start;voidWorld.game.advance(voidStart+.2);voidWorld.field.update(voidWorld.game.elapsed,voidWorld.geometry,()=>{});const voidState=json(voidWorld);
for(const kind of ['tap','burst']){const result=finish(new api.ForecastRollout(voidWorld.field,voidWorld.game,voidWorld.geometry,{kind,targetId:target(voidWorld)}));ok(!result.valid&&result.reason==='void'&&json(voidWorld)===voidState,kind+' projection cannot suggest a forbidden VOID input');}
const voidAgent=readyAgent(voidWorld,{kind:'tap',mode:'challenge'});ok(voidAgent.calls===0&&voidAgent.attempts>0&&voidAgent.best===null&&voidAgent.results.every(r=>r.confidence!=='STABLE'),'Invalid VOID candidates never count as completed valid tool calls or stable futures');
armed(voidWorld);const voidRestart=finish(new api.ForecastRollout(voidWorld.field,voidWorld.game,voidWorld.geometry,{kind:'restart',targetId:null,locked:true}));ok(voidRestart.valid,'Frozen VOID allows a conditional restart projection without advancing its live signal');
w=armed(world());invalid=finish(new api.ForecastRollout(w.field,w.game,w.geometry,{kind:'tap',targetId:target(w)}));ok(!invalid.valid&&invalid.reason==='locked','A frozen world cannot be forecast as immediate TAP ignition');
w=world();invalid=finish(new api.ForecastRollout(w.field,w.game,w.geometry,{kind:'restart'}));ok(!invalid.valid&&invalid.reason==='restart-unavailable','PHASE ANCHOR requires a real frozen world or explicit locked hypothesis');
for(const plan of [{kind:'unknown',targetId:1},{kind:'tap',targetId:99999},{kind:'tap',targetId:NaN}]){w=world();const before=json(w),r=finish(new api.ForecastRollout(w.field,w.game,w.geometry,plan));ok(!r.valid&&r.done&&json(w)===before,'Invalid forecast plan '+plan.kind+'/'+String(plan.targetId)+' fails safely');}
w=world();w.game.advance(90);invalid=finish(new api.ForecastRollout(w.field,w.game,w.geometry,{kind:'tap',targetId:target(w)}));ok(!invalid.valid&&invalid.reason==='inactive','Completed runs cannot start predictive actions');
for(const geo of [{...geometry,R:0},{...geometry,W:Infinity},{...geometry,cy:NaN}]){w=world();let rejected=false;try{api.cloneAgentWorld(w.field,w.game,geo);}catch(_){rejected=true;}ok(rejected,'Invalid forecast geometry is rejected before physics work');}
w=world();w.field.stars.push({...w.field.stars[0],id:999});let refused=false;try{api.cloneAgentWorld(w.field,w.game,w.geometry);}catch(_){refused=true;}ok(refused,'Oversized live world cannot enter forecasting');
for(const time of [59.99,89.99]){w=world({time:0});if(time>60)w.game.timeBonus=30;w.game.advance(time);w.field.update(w.game.elapsed,w.geometry,()=>{});const r=finish(new api.ForecastRollout(w.field,w.game,w.geometry,{kind:'tap',targetId:target(w)}));ok(r.done&&r.horizon<=1.5&&r.records.every(x=>Number.isFinite(x.x)&&Number.isFinite(x.y)&&x.time<=w.game.duration),'Forecast near '+time+'s remains finite and stops at the rewarded endpoint');}
w=world();let rollout=new api.ForecastRollout(w.field,w.game,w.geometry,{kind:'tap',targetId:target(w)},{horizon:100,dt:.00001});rollout.step(1e9);ok(rollout.ticks<=8,'A caller cannot bypass the eight-tick per-call budget');const bounded=finish(rollout);ok(bounded.steps<=180&&bounded.horizon<=1.5&&bounded.records.length<=24&&bounded.edges.length<=24,'Horizon, ticks and trace allocations have strict caps');
w=world();rollout=new api.ForecastRollout(w.field,w.game,w.geometry,{kind:'tap',targetId:target(w)},{horizon:0});ok(rollout.done&&rollout.result().steps===0,'Zero-horizon projection finishes without a work loop');
const graph=api.agentGraph(r1);ok(graph.nodes.length===r1.records.length&&graph.edges.length===r1.edges.length&&graph.nodes.every(n=>r1.ids.includes(n.id)),'ROUTER graph comes from simulated hit records and actual propagation edges');if(graph.nodes.length){graph.nodes[0].x=-100;ok(r1.records[0].x!==-100,'ROUTER output cannot mutate recorded physics traces');}
ok(api.agentEquivalent(r1,r2),'Equal fine/coarse physics records support STABLE classification');ok(!api.agentEquivalent(r1,{...r1,count:r1.count+1}),'Different predicted count must be treated as VOLATILE');
for(const level of [0,1,2,3,4]){w=world({level});const a=readyAgent(w,{kind:'tap'});ok(a.deployed.length===[0,0,2,3,4][level],'CORE level '+level+' deploys its intended visible cooperative role count');ok(a.roleCalls.SCOUT>0&&a.roleCalls.SIMULATOR>0&&a.roleCalls.ROUTER>0&&a.roleCalls.OPTIMIZER>0,'CORE level '+level+' still performs real scout, simulation, routing and comparison work');ok(a.results.length<=[2,2,3,3,4][level]&&a.calls<=8&&a.evaluated===a.results.length,'CORE level '+level+' obeys candidate and paired-rollout limits');}
w=world({level:4});const a=readyAgent(w,{kind:'tap'}),b=readyAgent(world({level:4}),{kind:'tap'});ok(a.best&&json(a.results)===json(b.results)&&json(a.best)===json(b.best),'Candidate ranking and tie breaking are deterministic');ok(a.results.every(r=>['STABLE','VOLATILE'].includes(r.confidence)&&r.graph&&Number.isFinite(r.value)),'Every evaluated candidate carries concordance, simulated graph and finite utility');
const stream=new api.AgenticWorld();for(let i=0;i<1000;i++){stream.noteInput('tap',.1);stream.noteChain(1);}ok(stream.history.length===24,'A thousand observations retain only twenty-four recent adaptation entries');stream.begin(w.field,w.game,w.geometry,{mode:'normal',kind:'tap'});ok(stream.strategy==='ADAPTIVE / CASCADE','Rapid or small-chain history changes normal candidate priorities');
const growth=new api.AgenticWorld();for(let i=0;i<4;i++)growth.noteChain(10);growth.begin(w.field,w.game,w.geometry,{mode:'normal',kind:'tap'});ok(growth.strategy==='ADAPTIVE / GROWTH','Large-chain history changes normal priorities toward absorbed growth');
stream.reset();ok(stream.history.length===0&&stream.best===null&&stream.results.length===0,'New runs clear temporary adaptation and old forecasts');
const fair=new api.AgenticWorld();fair.begin(w.field,w.game,w.geometry,{mode:'challenge',kind:'tap'});ok(!fair.noteInput('tap',.1)&&!fair.noteChain(1)&&fair.history.length===0,'Challenge does not learn different private player weights');while(!fair.step(8)){}const fixed=new api.AgenticWorld();for(let i=0;i<10;i++)fixed.noteInput('tap',.1);fixed.begin(w.field,w.game,w.geometry,{mode:'challenge',kind:'tap'});while(!fixed.step(8)){}ok(fair.strategy==='FIXED / CHALLENGE'&&fixed.strategy===fair.strategy&&json(fixed.results)===json(fair.results),'Challenge comparison stays fair despite a prior normal history');
const cancelled=new api.AgenticWorld();cancelled.begin(w.field,w.game,w.geometry,{kind:'tap'});const job=cancelled.job,serial=cancelled.serial;cancelled.cancel();ok(job.cancelled&&cancelled.job===null&&cancelled.serial>serial&&cancelled.step(),'Cancelling invalidates old jobs with no remaining work');
const replaced=new api.AgenticWorld();replaced.begin(w.field,w.game,w.geometry,{kind:'tap'});const oldJob=replaced.job;replaced.begin(w.field,w.game,w.geometry,{kind:'burst'});ok(oldJob.cancelled&&replaced.job.plan.kind==='burst'&&replaced.tool==='BURST SOLVER','A newer request replaces, rather than accumulates, stale projections');
w=armed(world());const before=json(w),phase=readyAgent(w,{kind:'restart',locked:true});ok(json(w)===before&&w.game.timeLockLeft===5,'ARMED projections leave live OVER DRIVE clock, signal and game elapsed frozen');ok(phase.results.length<=4&&phase.results[0].targetId===null&&phase.best&&phase.results.every(r=>r.tool==='PHASE ANCHOR'),'PHASE ANCHOR compares actual ARMED baseline with bounded extra selections');
const {environment}=require('./interaction.cjs');
const snapshot=e=>JSON.parse(e.el.modelSnapshot.textContent),worldView=e=>JSON.parse(e.el.worldSnapshot.textContent);
async function ui(){
 for(const event of ['visibilitychange','pagehide']){const ready=environment({search:'?rules=R3&qa=agentic',audioAvailable:false});await ready.advance(600);ready.el.modelButton.fire('click');if(event==='visibilitychange'){ready.doc.hidden=true;ready.doc.fire(event);}else ready.win.fire(event);const stopped=ready.el.modelSnapshot.textContent;ok(ready.timerCount()===0,'Pre-play '+event+' immediately cancels all queued forecast work');await ready.advance(1200);ok(ready.el.modelSnapshot.textContent===stopped,'Pre-play '+event+' cannot continue simulation or hidden DOM updates');}
 const sparse=environment({search:'?challenge='+seed+'&rules=R3&qa=agentic',audioAvailable:false});sparse.el.connect.fire('click');await sparse.advance(2300,200);let sparseModel=snapshot(sparse);
 ok(sparseModel.done&&sparseModel.evaluated>=2&&sparseModel.calls>=4,'A sparse 5 Hz paint cadence completes real parallel forecasts before they expire');
 ok(Number(sparse.el.syncValue.textContent)===0&&worldView(sparse).growth===0,'Completing a sparse-frame forecast cannot score or grow the live world');
 const held=environment({search:'?rules=R3&qa=agentic',audioAvailable:false});held.el.connect.fire('click');await held.advance(40);held.pointer('pointerdown');await held.advance(500);
 ok(snapshot(held).tool==='BURST SOLVER'&&held.el.burstCells.getAttribute('aria-label').includes('3回'),'A live CORE hold calls BURST SOLVER without spending a real cell');
 await held.advance(600);ok(snapshot(held).done&&snapshot(held).calls===2,'A held CORE completes both real burst forecast cadences');held.pointer('pointerup');await held.advance(120);
 ok(held.el.burstCells.getAttribute('aria-label').includes('2回'),'Only the human RELEASE spends the real CORE BURST');
 const e=environment({search:'?rules=R3&qa=agentic',audioAvailable:false});await e.advance(2000);ok(!e.el.connect.hidden&&worldView(e).elapsed===0&&Number(e.el.syncValue.textContent)===0,'Intro projection never starts gameplay or grants score');
 e.el.connect.fire('click');await e.advance(1750);let s=snapshot(e);
 ok(e.el.modelSlots.textContent==='◇ 2','Remaining prediction slots are visible without hover');ok(s.uses===2&&s.observed>0&&s.done&&s.best,'First-run automatic projection observes and evaluates an actual world');
 ok(!e.el.modelPanel.hidden&&e.el.modelTitle.textContent.includes('BEST PATH')&&e.el.modelTool.textContent==='CHAIN COMPILER','A completed projection exposes its path confidence and real tool');
 ok(e.el.modelStats.textContent.includes('BODIES')&&e.el.modelStats.textContent.includes('FUTURES')&&e.el.modelEstimate.textContent.includes('CHAIN'),'HUD statistics come from observed bodies and completed candidate futures');
 ok(Number(e.el.syncValue.textContent)===0&&Number(e.el.energyValue.textContent)===0&&worldView(e).growth===0&&worldView(e).waves===0,'Automatic forecast cannot ignite, grow or score the live world');
 const serial=s.serial;e.el.modelButton.fire('click');await e.advance(100);s=snapshot(e);ok(s.serial===serial&&s.uses===2,'Repeated clicks cannot bypass projection recharge');
 await e.advance(6000);ok(!e.el.modelButton.disabled,'MODEL becomes usable again after its world-time recharge');e.el.modelButton.fire('click');await e.advance(500);s=snapshot(e);ok(s.done&&s.uses===1&&s.best,'A manual request spends one bounded projection slot');
 await e.tap();ok(e.el.modelPanel.hidden,'Player input dismisses a stale projected path');
 await e.advance(6200);e.el.modelButton.fire('click');await e.advance(500);s=snapshot(e);ok(s.uses===0&&e.el.modelButton.disabled,'Three requests exhaust normal projection slots');
 e.win.fire('blur');await e.advance(150);ok(e.el.modelPanel.hidden&&e.el.modelButton.disabled,'Pause cancels stale projection and blocks new work');e.el.resume.fire('click');await e.advance(150);
 e.doc.hidden=true;e.doc.fire('visibilitychange');const pausedSnapshot=e.el.modelSnapshot.textContent;await e.advance(3000,1000);ok(e.rafCount()===0&&e.el.modelSnapshot.textContent===pausedSnapshot,'Hidden pages stop projection work and visible updates');e.doc.hidden=false;e.doc.fire('visibilitychange');e.el.resume.fire('click');await e.advance(92000,1000);
 ok(!e.el.result.hidden&&e.el.modelPanel.hidden&&e.el.modelButton.disabled,'Result closes forecasts and prevents further requests');e.el.reconnect.fire('click');await e.advance(100);s=snapshot(e);ok(s.uses===3&&s.best===null&&s.evaluated===0,'One-tap replay clears projected worlds and restores all slots');
 const challenge=environment({search:'?challenge='+seed+'&rules=R3&qa=agentic',audioAvailable:false,storageFail:true});challenge.el.connect.fire('click');await challenge.advance(1750);s=snapshot(challenge);ok(s.strategy==='FIXED / CHALLENGE'&&s.done,'Challenge forecasting uses fixed comparison despite unavailable storage');await challenge.advance(92000,1000);ok(!challenge.el.result.hidden,'Forecasting cannot prevent an R3 Challenge from completing');
 const signal=environment({search:'?challenge='+seed+'&rules=R3&qa=agentic',audioAvailable:false});signal.el.connect.fire('click');await signal.advance((voidStart+.2)*1000);const signalModel=snapshot(signal);signal.el.modelButton.fire('click');await signal.advance(100);ok(signal.el.modelButton.disabled&&signal.el.modelPanel.hidden&&signal.el.signalInstruction.textContent.includes('触らない'),'VOID retains the visible no-touch instruction instead of a competing projection');ok(snapshot(signal).uses===signalModel.uses&&snapshot(signal).serial===signalModel.serial,'Blocked VOID projection neither consumes a slot nor starts a job');
 for(const rules of ['R1','R2']){const old=environment({search:'?challenge='+seed+'&rules='+rules+'&qa=agentic',audioAvailable:false});old.el.connect.fire('click');await old.advance(1750);const view=worldView(old),model=snapshot(old);ok(view.rules===rules&&model.done&&model.tool==='CHAIN COMPILER','Archived '+rules+' keeps its own physical world while running local projections');}
 ok(Object.values(e.el).every(el=>!(/\b(?:NaN|Infinity|undefined)\b/.test(el.textContent+' '+el.innerHTML))),'Agentic UI exposes no invalid values or unresolved display strings');
 console.log(checks+' agentic checks passed. Real rendering, audio and device performance remain separate.');
}
ui().catch(error=>{console.error(error);process.exitCode=1;});
