#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const {environment}=require('./interaction.cjs'),html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const extract=n=>'//'+html.split('// '+n+'_BEGIN')[1].split('// '+n+'_END')[0];
const api=vm.runInNewContext(['SYNC_MODEL','REMOTE_MODEL','GALAXY_MODEL','GHOST_MODEL','STAR_MODEL','ORBIT_MODEL','GALAXY_FIELD','ASCENSION_MODEL','AGENTIC_MODEL'].map(extract).join('\n')+'\n({AscensionTest,AscensionRemoteTest,AscensionField,ASCENSION_STAGES,ASCENSION_STARS,universeSignature,cloneAgentWorld,ForecastRollout,AgenticWorld,agentRoles,parseChallenge,parseGhost,challengeURL,GhostRecorder,ghostURL,ghostDecode,ghostEncode,ghostSample,dailySeed})',{URL,URLSearchParams});
let checks=0;const ok=(v,label)=>{assert.ok(v,label);checks++;console.log('PASS '+label);},json=JSON.stringify,seed='A7F291C8',g={W:390,H:844,cx:195,cy:365,R:78,top:146,bottom:560};
function world(){const field=new api.AscensionField(seed),game=new api.AscensionRemoteTest(seed);game.start();return{field,game};}
function callback(w){return(s,count,p,from,group)=>{w.game.starBurst(count);w.game.absorb(s,count,group);w.field.setLevel(w.game.level);};}
function advance(w,d,dt=1/60){for(let t=0;t<d-1e-8;t+=dt){w.game.advance(Math.min(dt,d-t));if(!w.game.timeLockLeft&&w.game.state==='playing')w.field.update(w.game.elapsed,g,callback(w));}}
ok(api.ASCENSION_STARS.length===24,'Twenty-four named stellar designs are shipped');
ok(new Set(api.ASCENSION_STARS.map(s=>s.name)).size===24,'All English names are unique');
ok(new Set(api.ASCENSION_STARS.map(s=>s.visualId)).size===24,'Every named star has its own visual identity');
ok(new Set(api.ASCENSION_STARS.map(s=>[s.form,s.rays,s.shells,s.size].join(':'))).size===24,'Named geometry differs independently of color');
ok(new Set(api.ASCENSION_STARS.map(s=>s.size)).size>=5&&Math.max(...api.ASCENSION_STARS.map(s=>s.size))===2.6,'At least five stylized scales include giant and compact bodies');
for(let level=0;level<5;level++){const f=new api.AscensionField(seed);f.stars=[];f.setLevel(level);for(let i=0;i<30;i++)f.spawn(i);ok(f.stars.length===api.ASCENSION_STAGES[level].cap,'Level '+level+' obeys its active cap');ok(f.settings.mass===api.ASCENSION_STAGES[level].mass,'Level '+level+' exposes actual capture limit');}
let a=world(),b=world();advance(a,7);advance(b,7);ok(json(a.field)===json(b.field),'Identical R4 seed and world time reproduce influx and orbit');
const different=new api.AscensionField('91C8A7F2');ok(json(different.stars)!==json(a.field.stars),'A different seed changes spatial influx');
const small=new api.AscensionTest();small.start();ok(small.coreScale===.36&&small.level===0,'CORE starts at the small SEED scale');
for(const [mass,threshold] of [[1,10],[2,28],[3,56],[5,98]]){const before=small.growth;small.absorb({mass},5,{timeReward:0,simultaneous:3});ok(small.growth>before,'Actual mass and chain increase growth '+mass);small.growth=threshold;ok(small.level===[10,28,56,98].indexOf(threshold)+1,'Growth threshold '+threshold+' advances capability');}
ok(small.coreScale>.9,'CORE physically grows beyond the initial radius');
const target=new api.AscensionField(seed);target.stars=[];const heavy=target.spawn(0);Object.assign(heavy,{mass:4,state:'INBOUND',capture:null,duration:2});target.update(1.7,g,()=>{});ok(heavy.state==='SLINGSHOT'&&heavy.capture===false,'An excessive mass enters a curved slingshot');const hp=target.point(heavy,g);ok(!target.hit(hp.x,hp.y,g),'An uncapturable body cannot be ignited for free growth');target.update(5,g,()=>{});ok(!heavy.alive&&target.escaped===1,'Slingshot leaves the universe and releases its active slot');
target.stars=[];target.setLevel(4);const capture=target.spawn(0);capture.mass=4;target.update(1.7,g,()=>{});ok(capture.capture===true,'The same mass category becomes capturable after growth');target.update(40,g,()=>{});ok(capture.alive&&capture.state==='ORBIT','Captured bodies persist until a player or chain ignites them');
const named=new api.AscensionField(seed);named.setLevel(4);const names=[];for(let i=0;i<35;i++){named.stars=[];const s=named.spawn(i);if(s.name)names.push(s.name);}ok(names.length===24&&new Set(names).size===24,'A seeded deck draws all names without replacement');ok(named.namedPool.length===0,'Exhausted named deck stops reusing identities');named.reset(seed);ok(named.namedPool.length===24,'Reconnect restores the complete named deck');
const beforeReset=new api.AscensionField(seed);beforeReset.setLevel(4);beforeReset.stars=[];const first=beforeReset.spawn(0).name;named.setLevel(4);named.stars=[];ok(named.spawn(0).name===first,'Reset reproduces the named deck for the same seed');
const f=new api.AscensionField(seed);f.stars=[];f.setLevel(4);for(let i=0;i<7;i++){const s=f.spawn(-5);Object.assign(s,{mass:1,type:'fragment',name:null,visual:null,capture:true,state:'ORBIT',speed:0,ring:1.15,phase:i*.12});}f.time=3;const p=f.point(f.stars[0],g),events=[];f.trigger(p.x,p.y,3,g,(s,n)=>events.push({id:s.id,n,time:3}));ok(events.length===1&&!f.stars[0].alive,'Single tap immediately detonates the nearest body');ok(f.waves[0].radius<g.R,'Single tap wave is local');for(let t=3;t<4;t+=1/60)f.update(t,g,(s,n)=>events.push({id:s.id,n,time:t}));ok(events.length>=5&&f.bestChain>=5,'Local shockwave propagates at least five linked detonations');
const burst=new api.AscensionTest();burst.start();ok(!burst.coreBurst(.5)&&burst.coreBursts===3,'Early release consumes no CORE IMPULSE');for(let i=2;i>=0;i--)ok(burst.coreBurst(1.1)&&burst.coreBursts===i,'Three CORE impulses consume one cell each');ok(!burst.coreBurst(1.1),'Fourth CORE impulse is unavailable');
const nf=new api.AscensionField(seed);nf.stars=[];nf.setLevel(4);for(let i=0;i<3;i++){const s=nf.spawn(-5);Object.assign(s,{mass:1,type:'fragment',capture:true,state:'ORBIT',ring:1.2,phase:i*.3,speed:0});}nf.time=5;const np=nf.point(nf.stars[0],g),orig=nf.point(nf.stars[1],g);let novaBursts=0;nf.nova(np.x,np.y,5,g,()=>novaBursts++);ok(novaBursts===0&&nf.pendingNovas.length===1,'GRAVITY NOVA first contracts instead of instantly detonating');nf.update(5.15,g,()=>novaBursts++);ok(Math.hypot(nf.point(nf.stars[1],g).x-np.x,nf.point(nf.stars[1],g).y-np.y)<Math.hypot(orig.x-np.x,orig.y-np.y),'NOVA actually moves neighboring bodies toward its focus');nf.update(5.31,g,()=>novaBursts++);ok(novaBursts>=3&&nf.pendingNovas.length===0,'NOVA releases after the bounded contraction interval');
a=world();advance(a,4);Object.assign(a.game,{energy:100,score:650,taps:5,holds:2,novas:3,absorbed:9});ok(a.game.overdrive(),'Qualified OVER DRIVE starts');const frozen=json(a.field),elapsed=a.game.elapsed;a.game.advance(1);ok(a.game.elapsed===elapsed&&json(a.field)===frozen,'OVER DRIVE freezes world time and the complete field');const candidates=a.field.stars.filter(s=>s.alive&&s.mass<=a.field.settings.mass&&s.capture!==false).slice(0,3);for(const s of candidates){const p=a.field.point(s,g);a.field.arm(p.x,p.y,g);}ok(a.field.stars.filter(s=>s.state==='ARMED').length===3,'Three different bodies can be selected while stopped');const sp=a.field.point(candidates[0],g);ok(!a.field.arm(sp.x,sp.y,g),'Selecting an ARMED body does not duplicate it');let restarted=[];a.game.advance(4);a.field.restart(a.game.elapsed,g,(s,n,p,from,group)=>restarted.push({at:a.game.elapsed,id:s.id,group:group.id}));ok(restarted.length===3&&new Set(restarted.map(x=>x.at)).size===1&&new Set(restarted.map(x=>x.group)).size===1,'Restart detonates all selections at the same world instant and chain group');
a=world();advance(a,5);const initial=json(a),clone=api.cloneAgentWorld(a.field,a.game,g);ok(clone.rules==='R4'&&json(clone.field)===json(a.field),'WORLD MODEL preserves an isolated R4 universe');clone.field.namedPool.pop();ok(a.field.namedPool.length===24,'Forecast cannot consume the live named deck');const tid=a.field.stars.find(s=>s.alive&&s.capture!==false&&s.mass<=a.field.settings.mass).id,rollout=new api.ForecastRollout(a.field,a.game,g,{kind:'tap',targetId:tid});while(!rollout.done)rollout.step(8);ok(rollout.valid&&rollout.count>=1&&json(a)===initial,'Real R4 prediction is useful and never mutates the live game');
const expected=rollout.result(),actual=world();advance(actual,5);const root=actual.field.stars.find(s=>s.id===tid),pt=actual.field.point(root,g),ids=[],cg=actual.field.chainId+1;const cb=(s,n,p,from,group)=>{callback(actual)(s,n,p,from,group);if(group.id===cg)ids.push(s.id);};actual.field.trigger(pt.x,pt.y,actual.game.elapsed,g,cb);for(let i=0;i<90;i++){actual.game.advance(1/60);actual.field.update(actual.game.elapsed,g,cb);}ok(json(expected.ids)===json(ids),'Predicted R4 chain identities equal independent direct execution');
for(const level of [0,1,2,3,4])ok(api.agentRoles(level).length===[0,0,2,3,4][level],'Agent roles follow CORE level '+level);
for(const rules of ['R1','R2','R3','R4'])ok(!api.parseChallenge('?challenge='+seed+'&rules='+rules).invalid,'URL preserves '+rules+' compatibility');ok(new URL(api.challengeURL(seed,'https://dicek9750.github.io/astral-core-demo/')).searchParams.get('rules')==='R4','New shared universe explicitly uses R4');
const recordWorld=world(),rec=new api.GhostRecorder(seed,'R4');while(recordWorld.game.state==='playing'){recordWorld.game.advance(.1);rec.observe(recordWorld.game);}const record=rec.finish(recordWorld.game),url=api.ghostURL(seed,record,'https://dicek9750.github.io/astral-core-demo/','R4'),decoded=api.parseGhost(new URL(url).search,seed).data;ok(decoded?.version===4&&decoded.frames.length===61,'R4 Ghost retains 61 compact samples with explicit format four');ok(api.ghostEncode(decoded,seed,'R4')===new URL(url).searchParams.get('ghost'),'R4 codec is canonical after round trip');ok(url.length<1000,'R4 Ghost URL is realistically bounded');ok(!api.ghostDecode(new URL(url).searchParams.get('ghost'),seed,'R3'),'R4 record cannot be relabeled as old gameplay');ok(api.ghostSample(decoded,60).score===record.score,'Ghost ends at the exact recorded score');console.log('R4_SAMPLE_GHOST_URL '+url+'\nR4_URL_LENGTH '+url.length);
const sig=api.universeSignature(small);ok(sig.stage==='NOVA'&&sig.chain===5&&sig.text.includes('CHAIN 5'),'UNIVERSE SIGNATURE comes from actual final facts');
for(const dimension of [{...g,W:320,H:568,R:44,cx:160,cy:310,top:170,bottom:410},{...g,W:844,H:390,R:50,cx:285,cy:226,top:110,bottom:300},{...g,W:1920,H:1080,R:175,cx:960,cy:530,top:180,bottom:850}]){const w=world();let max=0;for(let i=0;i<5400&&w.game.state==='playing';i++){w.game.advance(1/60);w.field.update(w.game.elapsed,dimension,callback(w));if(i%90===0){const s=w.field.stars.find(s=>s.alive&&s.mass<=w.field.settings.mass&&s.capture!==false);if(s){const p=w.field.point(s,dimension);w.field.trigger(p.x,p.y,w.game.elapsed,dimension,callback(w));}}max=Math.max(max,w.field.stars.length);assert.ok(Number.isFinite(w.field.time),'Finite world clock');}ok(w.game.state==='result'&&max<=18&&w.field.waves.length<=24,'Complete '+dimension.W+' game stays within object caps');}
const driveSource=html.match(/function driveUsable\(\)\{[^}]*\}/)[0],drive=(stars)=>vm.runInNewContext(driveSource+'\ndriveUsable()',{game:{ready:true,absorb:()=>{}},starField:{rules:'R4',settings:{mass:1.3},stars}}),eligible={alive:true,mass:1,capture:true};
ok(!drive([eligible,eligible,{alive:true,mass:2,capture:null}]),'READY excludes a visible future mass that cannot be selected');ok(!drive([eligible,eligible,{alive:true,mass:1,capture:false}]),'READY excludes a slingshot that has left the capture contract');ok(drive([eligible,eligible,eligible]),'Three eligible bodies make R4 OVER DRIVE ready');
async function audio(){const freq=[],pan=[],voices=[];const param=(record=false)=>({value:0,setValueAtTime(v){if(record)freq.push(v);},exponentialRampToValueAtTime(){},setTargetAtTime(){}});const node=()=>({gain:param(),frequency:param(true),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),connect(){},disconnect(){},start(){},stop(){}});class Context{constructor(){this.state='running';this.currentTime=0;this.destination=node();}createGain(){return node();}createDynamicsCompressor(){return node();}createOscillator(){const n=node();voices.push(n);return n;}createStereoPanner(){const n=node();n.pan={set value(v){pan.push(v);}};return n;}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}}
const source='function createSoundEngine'+html.split('function createSoundEngine')[1].split('\nconst sound=createSoundEngine')[0],sound=vm.runInNewContext(source+'\ncreateSoundEngine()',{window:{AudioContext:Context}});sound.universe(0,0);ok(voices.length===0,'Adaptive atmosphere honors gesture-only AudioContext activation');await sound.unlock();sound.universe(0,0);const startFreq=freq[0],initial=voices.length;ok(initial===1,'SEED atmosphere is one quiet tonal layer');sound.universe(0,1);ok(voices.length===initial,'Universe ambience is bounded to one emission per 2.8 world seconds');freq.length=0;sound.universe(4,3);ok(voices.length===initial+3&&Math.min(...freq)<startFreq,'NOVA atmosphere adds lower bass and harmonic layers');ok(pan.some(v=>v<0)&&pan.some(v=>v>0),'Growth sound actually widens stereo placement');const beforeMute=voices.length;await sound.toggle();sound.universe(4,6);ok(voices.length===beforeMute,'Mute suppresses all adaptive layers');await sound.toggle();sound.universe(4,7);ok(voices.length>beforeMute,'Adaptive layers resume safely after a user sound gesture');}
async function ui(){const e=environment({search:'?qa=ascension',audioAvailable:false,storageFail:true});ok(e.el.heroTitle.textContent.includes('恒星')&&e.el.heroSub.textContent.includes('60秒'),'Unified opening shows the scale objective and initial time');ok(e.el.modeSwitch.hidden&&html.includes('.mode-switch{display:none!important}'),'Two-mode selector is absent from visible game UI');ok(/HOLD CORE/.test(e.el.hint.innerHTML),'First play explicitly assigns HOLD to CORE');e.el.connect.fire('click');await e.advance(3500);let w=JSON.parse(e.el.worldSnapshot.textContent);const s=w.active.find(s=>s.targetable&&s.x>30&&s.x<360&&s.y>150&&s.y<550);assert.ok(s,'Visible R4 tap target');const coords={clientX:s.x,clientY:s.y};const score=Number(e.el.syncValue.textContent);e.pointer('pointerdown',coords);await e.advance(35);e.pointer('pointerup',coords);ok(Number(e.el.syncValue.textContent)>score,'First celestial tap scores synchronously without a double-tap wait');await e.advance(90);e.pointer('pointerdown',coords);await e.advance(35);e.pointer('pointerup',coords);ok(e.el.eventTitle.textContent==='GRAVITY NOVA','Double action on the last detonation upgrades it to GRAVITY NOVA');await e.advance(350);e.pointer('pointerdown',{clientX:195,clientY:365.4});await e.advance(1100);e.pointer('pointerup',{clientX:195,clientY:365.4});ok(e.el.burstCells.getAttribute('aria-label').includes('2回'),'CORE-only ideal HOLD spends one impulse cell');await e.advance(92000,1000);ok(!e.el.result.hidden&&!e.el.universeSignature.hidden,'Unified R4 completes with its Universe Signature despite storage failure');e.el.shareChallenge.fire('click');await new Promise(r=>setImmediate(r));ok(!e.el.sharePanel.hidden&&e.el.shareUrl.selected&&new URL(e.el.shareUrl.value).searchParams.get('gver')==='4','First unified run shares a valid manually selectable R4 Ghost');const rival=environment({search:new URL(e.el.shareUrl.value).search,audioAvailable:false});ok(rival.el.app.classList.contains('duel'),'R4 Ghost automatically adds archived rival');rival.el.connect.fire('click');await rival.advance(92000,1000);ok(!rival.el.duelResult.hidden,'R4 Ghost Duel completes with an exact outcome');rival.el.shareChallenge.fire('click');await new Promise(r=>setImmediate(r));ok(new URL(rival.el.shareUrl.value).searchParams.get('gver')==='4','SEND REMATCH retains the R4 binary rules');console.log(checks+' ascension checks passed.');}
audio().then(ui).catch(e=>{console.error(e);process.exitCode=1;});
