#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const extract=name=>'//'+html.split('// '+name+'_BEGIN')[1].split('// '+name+'_END')[0];
const {RemoteTest,normalizeSeed,parseChallenge,challengePlan,dailySeed,challengeURL}=vm.runInNewContext(extract('SYNC_MODEL')+'\n'+extract('REMOTE_MODEL')+'\n({RemoteTest,normalizeSeed,parseChallenge,challengePlan,dailySeed,challengeURL})',{URL,URLSearchParams});
let n=0;function ok(v,label){assert.ok(v,label);n++;console.log('PASS '+label);}
function fresh(seed='A7F291C8'){const g=new RemoteTest(seed);g.start();return g;}
ok(normalizeSeed('a7f291c8')==='A7F291C8','Seed normalizes safely');
for(const value of ['<script>', 'A'.repeat(1000000),'A7F291C8%','あいうえおかきく','',' 12345678',null])ok(normalizeSeed(value)===null,'Reject invalid seed '+String(value).slice(0,12));
ok(parseChallenge('?challenge=a7f291c8').seed==='A7F291C8','URL parses normalized challenge');
for(const search of ['?challenge=%ZZ','?challenge=A7F291C8&challenge=12345678','?challenge=%3Cscript%3E','?challenge='+ 'A'.repeat(1000000)])ok(parseChallenge(search).invalid&&!parseChallenge(search).seed,'Malformed or oversized query falls back');
ok(!parseChallenge('').seed&&!parseChallenge('').invalid,'Normal URL remains normal');
ok(JSON.stringify(challengePlan('A7F291C8'))===JSON.stringify(challengePlan('a7f291c8')),'Same seed reproduces every event and beat');
ok(JSON.stringify(challengePlan('A7F291C8'))!==JSON.stringify(challengePlan('12345678')),'Different seeds change challenge');
let fair=true;for(let i=0;i<200;i++){const plan=challengePlan(i.toString(16).padStart(8,'0'));const counts={};for(const e of plan){counts[e.kind]=(counts[e.kind]||0)+1;if(Math.abs(e.end-e.start-3.2)>.0001)fair=false;}if(Object.values(counts).some(c=>c!==2)||plan.length!==10||plan.at(-1).end>56)fair=false;}ok(fair,'200 seeds: exactly two of each signal, equal duration and +1000 potential');
let g=fresh();for(const e of g.events){g.advance(e.start-g.elapsed+.01);if(e.kind==='VOID'){g.advance(e.end+.41-g.elapsed);continue;}if(e.kind==='PULSE'){g.advance(e.beat-.01);g.input('tap');}if(e.kind==='JAM'){g.input('tap');g.advance(.55);g.input('tap');}if(e.kind==='PHASE SHIFT'){g.advance(1.1);g.input('hold',1.1);}if(e.kind==='OVERLOAD')g.input('nova');g.advance(e.end+.41-g.elapsed);}ok(g.signalWins===10&&g.signalScore===1000,'All five responses yield the same maximum bonus');g.advance(60);ok(g.state==='result'&&Number.isSafeInteger(g.totalScore),'Challenge finishes with an integer comparable score');g.start();ok(g.elapsed===0&&g.signalScore===0&&g.signalWins===0&&!g.events.some(e=>e.success),'Retry resets all event state with same seed');
g=fresh();const jam=g.events.find(e=>e.kind==='JAM');g.advance(jam.start+.1);g.input('tap');for(let i=0;i<15;i++){g.advance(.1);g.input('tap');}ok(!jam.success&&jam.penalty===30,'JAM spam fails, with bounded penalties');
g=fresh();const v=g.events.find(e=>e.kind==='VOID');g.advance(v.start-.1);g.advance(.2,true);g.advance(v.end+.5-g.elapsed);ok(v.touched&&!v.success&&v.penalty===30,'Holding across VOID counts as input');
g=fresh();g.advance(v.start-.2);Object.assign(g,{combo:20,lastAction:g.elapsed,lastInput:g.elapsed});g.advance(3.4);ok(g.combo===20,'Quiet VOID preserves combo');
g=fresh();const pulse=g.events.find(e=>e.kind==='PULSE');g.advance(pulse.start+pulse.beat);g.advance(.33);g.input('tap',0,pulse.start+pulse.beat);ok(pulse.success,'Deferred taps use physical release timestamp for pulse accuracy');
g=fresh();const p2=g.events.find(e=>e.kind==='PULSE');g.advance(p2.end-.1);g.advance(.33);const r=g.input('tap',0,p2.end-.1);ok(r.ok&&!p2.settled,'Event settlement allows the double-tap decision window');
const url=challengeURL('a7f291c8','https://dicek9750.github.io/astral-core-demo/?junk=x#private');ok(url==='https://dicek9750.github.io/astral-core-demo/?challenge=A7F291C8&rules=R1','Shared URL contains only canonical seed and rules');
ok(dailySeed(new Date('2026-09-25T15:00:00Z')).day==='2026.09.26','Daily rolls over exactly at midnight JST');ok(dailySeed(new Date('2026-09-25T14:59:59Z')).seed!==dailySeed(new Date('2026-09-25T15:00:00Z')).seed,'Daily changes at JST boundary');
// Existing top-state conditions remain available inside Challenge.
g=fresh();Object.assign(g,{elapsed:58,score:1300,combo:20,maxCombo:20,goodTaps:12,holds:6,novas:6,taps:20,driveLeft:8,driveCount:2,driveActions:7,driveHold:true,driveNova:true,lastInput:57.4,lastAction:57.4});g.input('tap');ok(g.singularity&&g.rank[0]==='SS','Challenge retains SINGULARITY and SS');
const {environment}=require('./interaction.cjs');
async function ui(){let e=environment({search:'?challenge=A7F291C8',audioAvailable:false});ok(e.el.remoteInfo.hidden===false&&e.el.challengeMode.getAttribute('aria-pressed')==='true','Challenge URL selects remote immediately');e.el.connect.fire('click');await e.advance(9000,250);ok(!e.el.signalBanner.hidden&&e.el.signalType.textContent.includes('UNKNOWN'),'Unknown signal displays a persistent short instruction');e.win.fire('blur');const time=e.el.timeValue.textContent;await e.advance(4000,1000);ok(e.el.timeValue.textContent===time,'Pause freezes challenge time and signal');e.el.resume.fire('click');await e.advance(61000,1000);ok(!e.el.result.hidden&&!e.el.remoteResult.hidden&&e.el.resultChallenge.textContent.includes('A7F2-91C8'),'Challenge result shows score and full challenge ID');e.el.shareChallenge.fire('click');await new Promise(resolve=>setImmediate(resolve));ok(!e.el.sharePanel.hidden&&e.el.shareUrl.selected&&e.el.shareUrl.value.includes('challenge=A7F291C8'),'No Share or clipboard API: selectable canonical URL');ok(!e.el.shareChallenge.disabled,'Share failure never leaves button locked');e.el.reconnect.fire('click');await e.advance(150);ok(e.el.result.hidden&&e.el.timeValue.textContent==='60'&&e.el.sharePanel.hidden,'Challenge reconnect clears result and fallback panel');
let copied='';e=environment({search:'?challenge=A7F291C8',clipboard:{writeText:async t=>{copied=t;}}});e.el.connect.fire('click');await e.advance(61000,1000);e.el.shareChallenge.fire('click');await new Promise(resolve=>setImmediate(resolve));ok(copied.includes('challenge=A7F291C8')&&e.el.shareStatus.textContent.includes('コピーしました'),'Clipboard fallback succeeds');
let shared;e=environment({search:'?challenge=A7F291C8',share:async data=>{shared=data;}});e.el.connect.fire('click');await e.advance(61000,1000);e.el.shareChallenge.fire('click');await new Promise(resolve=>setImmediate(resolve));ok(shared.url.includes('rules=R1')&&shared.text.includes('SCORE'),'Web Share receives score text and canonical URL');
e=environment({search:'?challenge=A7F291C8',storageFail:true,share:async()=>{throw Object.assign(Error(),{name:'AbortError'});}});e.el.connect.fire('click');await e.advance(61000,1000);e.el.shareChallenge.fire('click');await new Promise(resolve=>setImmediate(resolve));ok(!e.el.result.hidden&&e.el.resultDelta.textContent.includes('今回のみ')&&!e.el.shareChallenge.disabled&&e.el.sharePanel.hidden,'Storage failure and native share cancellation stay usable');
e=environment({search:'?challenge=%3Cscript%3E'});ok(e.el.remoteInfo.hidden&&e.el.heroSub.textContent.includes('無効'),'Invalid challenge UI safely falls back to normal');e.el.challengeMode.fire('click');ok(e.el.challengeLabel.textContent.includes('A7F2-91C8'),'Create challenge uses random seed without device identity');e.el.dailyMode.fire('click');ok(e.el.challengeLabel.textContent.includes('DAILY CORE'),'Daily is available as one small option');e.el.normalMode.fire('click');ok(e.el.normalMode.getAttribute('aria-pressed')==='true','Can return to normal before starting');
e=environment({search:'?challenge=A7F291C8',share:async()=>{throw Error('policy');},clipboard:{writeText:async()=>{throw Error('denied');}}});e.el.connect.fire('click');await e.advance(61000,1000);e.el.shareChallenge.fire('click');await new Promise(resolve=>setImmediate(resolve));ok(!e.el.sharePanel.hidden&&e.el.shareUrl.selected&&!e.el.shareChallenge.disabled,'Rejected share and clipboard fall back to manual selection');
e.el.backMode.fire('click');ok(e.el.result.hidden&&!e.el.connect.hidden,'Result returns to mode selector');
console.log(`${n} challenge checks passed.`);}
ui().catch(e=>{console.error(e);process.exitCode=1;});
