#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const extract=name=>'//'+html.split('// '+name+'_BEGIN')[1].split('// '+name+'_END')[0];
const exportsList='RemoteTest,GhostRecorder,GhostRace,ghostEncode,ghostDecode,ghostURL,parseGhost,ghostSample,duelOutcome,ghostBase64,ghostUnbase64,ghostHash';
const api=vm.runInNewContext(['SYNC_MODEL','REMOTE_MODEL','GHOST_MODEL'].map(extract).join('\n')+'\n({'+exportsList+'})',{URL,URLSearchParams});
const {RemoteTest,GhostRecorder,GhostRace,ghostEncode,ghostDecode,ghostURL,parseGhost,ghostSample,duelOutcome,ghostBase64,ghostUnbase64,ghostHash}=api;
let checks=0;function ok(value,label){assert.ok(value,label);checks++;console.log('PASS '+label);}
const seed='A7F291C8',base='https://dicek9750.github.io/astral-core-demo/';
function recorded({quiet=false,observe=true}={}){const g=new RemoteTest(seed),r=new GhostRecorder(seed);g.start();const watch=()=>{if(observe)r.observe(g);};watch();if(quiet){g.advance(60);watch();}else{while(g.elapsed<60){for(const [kind,wait,held]of[['tap',.55,0],['tap',.55,0],['hold',1.1,1.1],['nova',.4,0]]){g.advance(wait);watch();g.input(kind,held);watch();if(g.ready){g.overdrive();watch();}}g.advance(.65);watch();}}return{g,record:r.finish(g)};}
const run=recorded(),record=run.record,encoded=ghostEncode(record,seed),decoded=ghostDecode(encoded,seed),url=ghostURL(seed,record,base);
ok(record.frames.length===61,'Recorder stores exactly 61 samples, including endpoints');
ok(!!decoded&&decoded.score===record.score&&decoded.sync===record.sync&&decoded.coreId===record.coreId&&decoded.rank===record.rank,'Binary round trip preserves exact final results');
ok(decoded.frames.every((f,i)=>Math.abs(f.score-record.frames[i].score)<=5&&Math.abs(f.sync-record.frames[i].sync)<=.51&&f.combo===record.frames[i].combo&&f.flags===record.frames[i].flags),'Intermediate scores within 5 points and sync within 0.5%, all flags and combos preserved');
ok(ghostEncode(decoded,seed)===encoded,'Canonical format can be decoded and encoded identically');
ok(/^[A-Za-z0-9_-]+$/.test(encoded)&&!url.includes('%'),'URL-safe encoding needs no escaping');
ok(url.length<500,'A complete mixed run fits under 500 URL characters');console.log('URL_LENGTH',url.length,'PAYLOAD_LENGTH',encoded.length,'SCORE',decoded.score);
ok(recorded({observe:false}).g.totalScore===run.g.totalScore,'Recording never changes Challenge scoring');
ok(!ghostDecode(encoded,'12345678'),'Ghost is bound to its original Challenge Seed');
for(const payload of ['',encoded.slice(1),encoded+'A','<script>', 'A'.repeat(1000000),encoded.slice(0,-1)+'!'])ok(ghostDecode(payload,seed)===null,'Reject malformed ghost '+payload.slice(0,12));
const search=new URL(url).search;ok(parseGhost(search,seed).data.score===record.score,'URL parser recognizes version 1 record');
for(const tail of ['&gver=2','&gver=0','&gver=x','&ghost='+encoded,'&rules=R1'])ok(parseGhost(search+tail,seed).invalid,'Duplicate or unknown parameters rejected');
ok(parseGhost(search.replace('gver=1','gver=2'),seed).invalid,'Unknown version falls back');ok(parseGhost(search.replace('gver=1','gver=0'),seed).invalid,'Old unsupported version falls back');ok(parseGhost(search.replace('rules=R1','rules=R2'),seed).invalid,'Ghost cannot silently use another rules version');ok(!parseGhost('?challenge='+seed,seed).invalid,'Ordinary Challenge stays ordinary');ok(parseGhost('?ghost='+'A'.repeat(1000000),seed).invalid,'Oversized query rejected before decoding');
const bytes=ghostUnbase64(encoded);const corrupted=bytes.slice();corrupted[30]^=1;ok(!ghostDecode(ghostBase64(corrupted),seed),'Checksum detects accidental data modification');
function tamper(fn){const b=bytes.slice();fn(b);const h=ghostHash(b.slice(0,-4));for(let i=0;i<4;i++)b[b.length-4+i]=(h>>>((3-i)*8))&255;return ghostDecode(ghostBase64(b),seed);}
ok(!tamper(b=>{b[10]=255;}),'Even a recomputed checksum cannot permit enormous scores');ok(!tamper(b=>{b[16]=99;}),'Invalid rank rejected');ok(!tamper(b=>{b[24]=255;}),'Invalid sample sync rejected');ok(!tamper(b=>{b[26]=255;}),'Unknown sample flags rejected');
ok(ghostSample(decoded,0).score===0&&ghostSample(decoded,60).score===decoded.score,'Replay begins at zero and ends at exact rival score');const midway=ghostSample(decoded,10.5);ok(midway.score===Math.round((decoded.frames[10].score+decoded.frames[11].score)/2),'Timeline interpolates neighboring samples in O(1)');ok(ghostSample(decoded,-5).score===0&&ghostSample(decoded,Infinity).score===0&&ghostSample(decoded,100).score===decoded.score,'Replay time bounds cannot corrupt display');
let race=new GhostRace(decoded),events=0,once=true;for(let t=0;t<=60;t++){const s=race.update(t,0);events|=s.events;if(race.update(t,0).events!==0)once=false;}ok(once,'Every important event fires only once across all 61 timeline boundaries');ok((events&4)&&(events&8)&&(events&16),'NOVA, OVERDRIVE, SINGULARITY echoes all replay');
race=new GhostRace(decoded);race.update(5,-100);ok(race.update(6,100000).overtake,'Crossing from behind to ahead triggers OVERTAKE');race.update(6.5,-100);ok(!race.update(7,100000).overtake,'Overtake cooldown suppresses rapid oscillation');race.update(10,-100);ok(race.update(11,100000).overtake,'A later genuine overtake can return');
ok(duelOutcome(100,99).label==='VICTORY'&&duelOutcome(99,100).label==='DEFEAT'&&duelOutcome(100,100).label==='DRAW','Victory, defeat and draw use exact final points');
ok(new URL(ghostURL(seed,record,url)).searchParams.getAll('ghost').length===1&&ghostURL(seed,record,url).length===url.length,'Rematch replaces the old ghost without growing a URL chain');
// A large gap without inputs must not apply a later score to earlier seconds.
const gapGame=new RemoteTest(seed),gapRecord=new GhostRecorder(seed);gapGame.start();gapGame.advance(.5);gapGame.input('hold',1.1);gapRecord.observe(gapGame);const scoreBefore=gapGame.totalScore;gapGame.advance(4);gapGame.input('hold',1.1);gapRecord.observe(gapGame);ok(gapRecord.frames.slice(1,5).every(f=>f.score===scoreBefore),'Stalled frames never backdate a later action');
const worst=recorded({quiet:true}).record;worst.frames=worst.frames.map((f,i)=>({...f,score:i%2?2500:0}));const worstURL=ghostURL(seed,worst,base);ok(worstURL.length<1000,'Worst permitted per-second deltas still fit below 1000 characters');console.log('WORST_URL_LENGTH',worstURL.length);const negative=ghostDecode(new URL(worstURL).searchParams.get('ghost'),seed);ok(negative.frames[1].score===2500&&negative.frames[2].score===0,'Signed deltas preserve falling scores');
const {environment}=require('./interaction.cjs'),settle=()=>new Promise(r=>setImmediate(r));
async function ui(){let shared=null;const e=environment({search,share:async data=>{shared=data;},audioAvailable:false});ok(e.el.app.classList.contains('duel')&&e.el.heroSub.textContent==='INCOMING GHOST DUEL'&&e.el.challengeLabel.textContent.includes(record.coreId),'Valid Ghost URL selects duel with archived rival identity');e.el.connect.fire('click');await e.advance(5000,250);ok(Number(e.el.rivalScore.textContent)>0&&e.el.stageMode.textContent==='RIVAL LEADS','Archived rival score advances with the game');e.win.fire('blur');const rivalAtPause=e.el.rivalScore.textContent;await e.advance(10000,1000);ok(e.el.rivalScore.textContent===rivalAtPause,'Pause freezes rival alongside player');e.el.resume.fire('click');await e.advance(61000,1000);ok(!e.el.duelResult.hidden&&e.el.duelOutcome.textContent==='DEFEAT'&&Number(e.el.duelRivalFinal.textContent)===decoded.score,'Real controller reaches DEFEAT with exact archived result');e.el.shareChallenge.fire('click');await settle();const rematch=new URL(shared.url),ownGhost=parseGhost(rematch.search,seed).data;ok(shared.title.includes('GHOST DUEL')&&ownGhost&&ownGhost.score===Number(e.el.duelYourFinal.textContent)&&ownGhost.coreId!==decoded.coreId,'SEND REMATCH shares current player, not incoming rival');e.el.shareSeedOnly.fire('click');await settle();ok(!new URL(shared.url).searchParams.has('ghost')&&new URL(shared.url).searchParams.get('challenge')===seed,'SEED ONLY preserves ordinary Challenge sharing');e.el.reconnect.fire('click');ok(e.el.duelResult.hidden&&e.el.rivalScore.textContent==='0'&&e.el.timeValue.textContent==='60','Rematch replay resets ghost clock to zero');
const quiet=recorded({quiet:true}).record,quietSearch=new URL(ghostURL(seed,quiet,base)).search;let d=environment({search:quietSearch,audioAvailable:false,storageFail:true});d.el.connect.fire('click');await d.advance(61000,1000);ok(d.el.duelOutcome.textContent==='DRAW','Controller reaches DRAW even when storage fails');d.el.shareChallenge.fire('click');await settle();ok(!d.el.sharePanel.hidden&&d.el.shareUrl.selected&&parseGhost(new URL(d.el.shareUrl.value).search,seed).data,'Without Share or Clipboard APIs, ghost URL remains manually selectable');
d=environment({search:quietSearch,audioAvailable:false});d.el.connect.fire('click');for(let i=0;i<3;i++){d.pointer('pointerdown');await d.advance(1100);d.pointer('pointerup');await d.advance(100);}await d.advance(61000,1000);ok(d.el.duelOutcome.textContent==='VICTORY'&&Number(d.el.duelYourFinal.textContent)>0,'Controller reaches VICTORY after valid player input');
for(const query of ['?challenge='+seed+'&gver=999&ghost='+encoded,'?challenge='+seed+'&gver=1&ghost=broken']){const bad=environment({search:query});ok(!bad.el.app.classList.contains('duel')&&bad.el.challengeMode.getAttribute('aria-pressed')==='true'&&bad.el.heroSub.textContent.includes('Ghost'),'Invalid ghost safely keeps the valid Challenge');}
const normal=environment();ok(!normal.el.app.classList.contains('duel'),'Normal URL never creates a rival');normal.el.challengeMode.fire('click');normal.el.dailyMode.fire('click');ok(normal.el.challengeLabel.textContent.includes('DAILY CORE')&&!normal.el.app.classList.contains('duel'),'Daily remains available independently of Ghost');
console.log(`${checks} ghost checks passed.`);}
if(require.main===module)ui().catch(e=>{console.error(e);process.exitCode=1;});
module.exports={record,encoded,url,api};
