#!/usr/bin/env node
'use strict';
// Runs the shipped script with minimal browser fakes; this does not test rendering,
// real sound, browser gesture policy, touch hardware, or actual performance.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const script=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');
function environment({reduced=false,audioAvailable=true,storageFail=false,stored=null}={}){
 let now=1000,serial=0,drawCalls=0;const rafs=new Map(),timers=new Map(),audioContexts=[],vibrations=[];
 class Events{constructor(){this.listeners={};}addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}removeEventListener(type,fn){this.listeners[type]=(this.listeners[type]||[]).filter(f=>f!==fn);}fire(type,fields={}){const e={type,target:this,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;},...fields};for(const fn of this.listeners[type]||[])fn(e);return e;}}
 class Classes{constructor(v=''){this.values=new Set(v.split(/\s+/).filter(Boolean));}add(v){this.values.add(v);}remove(v){this.values.delete(v);}contains(v){return this.values.has(v);}toggle(v,on){if(on===undefined)on=!this.values.has(v);on?this.add(v):this.remove(v);return on;}}
 const draw=new Proxy({createRadialGradient(){return{addColorStop(){}};}},{get(target,key){if(key in target)return target[key];return(...args)=>{drawCalls++;for(const value of args)if(typeof value==='number')assert.ok(Number.isFinite(value),`Canvas ${String(key)} received ${value}`);if(key==='arc')assert.ok(args[2]>=0,'Canvas arc radius must be nonnegative');};},set(target,key,value){target[key]=value;return true;}});
 class Element extends Events{constructor(tag='div',attrs=''){super();this.tagName=tag.toUpperCase();this.attributes={};for(const m of attrs.matchAll(/([\w-]+)\s*=\s*["']([^"']*)["']/g))this.attributes[m[1]]=m[2];this.id=this.attributes.id||'';this.hidden=/\bhidden(?:\s|>|$)/.test(attrs);this.classList=new Classes(this.attributes.class);this.style={setProperty(name,value){this[name]=value;}};this.textContent='';this.innerHTML='';this.captures=new Set();this.width=300;this.height=150;}focus(){doc.activeElement=this;}getContext(){return draw;}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]??null;}getBoundingClientRect(){return this.id==='stage'?{left:22,top:64,width:346,height:548}:{left:0,top:0,width:390,height:844};}setPointerCapture(id){this.captures.add(id);}hasPointerCapture(id){return this.captures.has(id);}releasePointerCapture(id){this.captures.delete(id);}closest(){return['BUTTON','INPUT','SELECT','TEXTAREA'].includes(this.tagName)?this:null;}}
 const elements={};for(const m of html.matchAll(/<([a-z][\w-]*)\b([^>]*\bid\s*=\s*["'][^"']+["'][^>]*)>/gi)){const el=new Element(m[1],m[2]);elements[el.id]=el;}
 const doc=new Events();doc.hidden=false;doc.body=new Element('body');doc.getElementById=id=>{assert.ok(elements[id],'Missing element '+id);return elements[id];};doc.createElement=tag=>new Element(tag);
 const win=new Events();const motion=new Events();motion.matches=reduced;motion.addListener=fn=>motion.addEventListener('change',fn);
 const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){},linearRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}});
 const node=()=>({gain:param(),frequency:param(),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),connect(){return this;},disconnect(){},start(){},stop(){}});
 class FakeAudioContext{constructor(){this.state='suspended';this.destination=node();this.resumeCalls=0;this.suspendCalls=0;audioContexts.push(this);}get currentTime(){return now/1000;}createGain(){return node();}createDynamicsCompressor(){return node();}createOscillator(){return node();}resume(){this.resumeCalls++;this.state='running';this.onstatechange?.();return Promise.resolve();}suspend(){this.suspendCalls++;this.state='suspended';this.onstatechange?.();return Promise.resolve();}}
 const timer=(fn,delay,repeat)=>{const id=++serial;timers.set(id,{fn,due:now+(Number(delay)||0),repeat});return id;};
 let storedValue=stored;const storage={getItem(){if(storageFail)throw Error('blocked');return storedValue;},setItem(k,v){if(storageFail)throw Error('quota');storedValue=v;}};
 const globals={console,localStorage:storage,document:doc,performance:{now:()=>now},navigator:{vibrate:p=>vibrations.push(p)},devicePixelRatio:3,matchMedia:()=>motion,ResizeObserver:class{observe(){}disconnect(){}},requestAnimationFrame:fn=>{const id=++serial;rafs.set(id,fn);return id;},cancelAnimationFrame:id=>rafs.delete(id),setInterval:(fn,ms)=>timer(fn,ms,ms),clearInterval:id=>timers.delete(id),setTimeout:(fn,ms)=>timer(fn,ms,0),clearTimeout:id=>timers.delete(id),addEventListener:win.addEventListener.bind(win),removeEventListener:win.removeEventListener.bind(win)};
 if(audioAvailable)globals.AudioContext=FakeAudioContext;globals.window=globals;
 vm.runInNewContext(script,globals,{filename:'index.html',timeout:3000});
 async function advance(ms,step=1000/60){const end=now+ms;while(now<end-.001){now=Math.min(end,now+step);for(const [id,task] of [...timers])if(task.due<=now){if(task.repeat)task.due+=task.repeat;else timers.delete(id);task.fn();}const queue=[...rafs];rafs.clear();for(const [,fn]of queue)fn(now);await Promise.resolve();}}
 function pointer(type,extra={}){return elements.stage.fire(type,{pointerId:1,isPrimary:true,button:0,clientX:195,clientY:320,target:elements.coreTarget,...extra});}
 async function tap(extra={}){pointer('pointerdown',extra);await advance(65);pointer('pointerup',extra);await Promise.resolve();}
 return{el:elements,win,doc,advance,pointer,tap,audioContexts,vibrations,storage:()=>storedValue,rafCount:()=>rafs.size,timerCount:()=>timers.size,drawCalls:()=>drawCalls};
}
let passed=0;function ok(condition,message){assert.ok(condition,message);passed++;console.log('PASS '+message);}
async function run(){
 const e=environment();await e.advance(300);ok(e.audioContexts.length===0,'Boot never opens AudioContext');
 e.el.connect.fire('click');await e.advance(50);ok(e.el.connect.hidden&&!e.el.overdrive.hidden&&e.el.linkState.textContent==='LINKED','Connect starts the test');ok(e.audioContexts.length===1&&e.el.sound.getAttribute('aria-pressed')==='true','Gesture enables one AudioContext');
 await e.tap();await e.advance(350);ok(Number(e.el.energyValue.textContent)>0&&Number(e.el.syncValue.textContent)>0,'Tap raises visible energy and sync');ok(!e.el.stage.hasPointerCapture(1),'Tap releases pointer capture');
 await e.advance(400);e.pointer('pointerdown');await e.advance(1100);ok(e.el.coreStatus.textContent==='RELEASE NOW','Ideal hold has a release cue');e.pointer('pointerup',{clientX:410});ok(e.el.eventTitle.textContent==='PERFECT CHARGE'&&!e.el.stage.hasPointerCapture(1),'Captured release outside core scores charge');
 await e.advance(450);const beforeNova=Number(e.el.energyValue.textContent);await e.tap();await e.advance(80);await e.tap();ok(e.el.eventTitle.textContent==='N O V A','Double tap triggers NOVA');ok(Number(e.el.energyValue.textContent)===beforeNova+14,'Double tap is not also scored as a normal tap');
 await e.advance(450);await e.tap();await e.advance(80);await e.tap();ok(e.el.eventTitle.textContent==='NOVA RECHARGING','NOVA cooldown gives feedback');
 ok(e.el.overdrive.disabled,'Unqualified OVERDRIVE stays locked');
 e.pointer('pointerdown');await e.advance(650);e.pointer('pointerdown',{pointerId:2,isPrimary:false});e.pointer('pointercancel',{pointerId:2,isPrimary:false});await e.advance(150);ok(e.el.stage.hasPointerCapture(1)&&e.el.coreStatus.textContent==='CHARGING','Secondary cancellation preserves primary charge');e.pointer('pointerup',{pointerId:2,isPrimary:false});ok(e.el.stage.hasPointerCapture(1),'Secondary release cannot finish charge');e.pointer('pointercancel');await e.advance(120);ok(!e.el.stage.hasPointerCapture(1)&&e.el.coreStatus.textContent.startsWith('NOVA'),'Primary cancellation clears charge');
 e.pointer('pointerdown');await e.advance(700);e.pointer('lostpointercapture');await e.advance(120);ok(e.el.coreStatus.textContent.startsWith('NOVA'),'Lost capture resets charge');
 e.el.coreTarget.fire('keydown',{code:'Space',repeat:false});await e.advance(700);e.el.coreTarget.fire('blur');await e.advance(120);ok(e.el.coreStatus.textContent.startsWith('NOVA'),'Keyboard blur cannot leave charge stuck');
 e.el.sound.fire('click');await Promise.resolve();await Promise.resolve();ok(e.el.sound.getAttribute('aria-pressed')==='false','Mute updates state');await e.tap();ok(e.audioContexts[0].state==='suspended','Further taps respect intentional mute');e.el.sound.fire('click');await Promise.resolve();await Promise.resolve();ok(e.el.sound.getAttribute('aria-pressed')==='true','Sound enables again');
 e.doc.hidden=true;e.doc.fire('visibilitychange');const drawn=e.drawCalls(),time=e.el.timeValue.textContent;await e.advance(10000,1000);ok(e.rafCount()===0&&e.drawCalls()===drawn,'Hidden page stops rendering');ok(e.audioContexts[0].state==='suspended'&&e.timerCount()===0,'Hidden page suspends audio and timer');e.doc.hidden=false;e.doc.fire('visibilitychange');await e.advance(150);ok(e.rafCount()===1&&e.drawCalls()>drawn,'Visible resumes one render loop');ok(!e.el.pausePanel.hidden&&e.el.timeValue.textContent===time,'Background time does not consume the run');e.el.resume.fire('click');await e.advance(1200);ok(e.el.pausePanel.hidden&&Number(e.el.timeValue.textContent)<Number(time),'Resume continues the timer');
 e.win.fire('pagehide');ok(e.rafCount()===0&&e.timerCount()===0,'Pagehide clears work');e.win.fire('pageshow');await e.advance(80);ok(e.rafCount()===1&&e.timerCount()===1,'Pageshow restores one loop and clock');e.el.resume.fire('click');
 await e.advance(61000,1000);ok(!e.el.result.hidden&&e.el.timeValue.textContent==='00','60 seconds shows result');ok(/^[0-9A-F]{4}-[0-9A-F]{4}$/.test(e.el.coreId.textContent),'Result shows deterministic CORE ID');ok(e.el.resultNova.textContent==='1','Result counts successful NOVA only');ok(e.el.coreTarget.disabled&&e.el.overdrive.hidden,'Result prevents gameplay');const finalSync=e.el.resultSync.textContent;await e.tap();ok(e.el.resultSync.textContent===finalSync,'Post-result input cannot change score');ok(JSON.parse(e.storage()).sync>=0,'Best result is saved');
 e.el.reconnect.fire('click');await e.advance(120);ok(e.el.result.hidden&&e.el.timeValue.textContent==='60'&&e.el.syncValue.textContent==='0.0'&&e.el.comboValue.textContent==='0','One-tap replay resets timer and statistics');ok(e.rafCount()===1&&e.timerCount()===1&&e.audioContexts.length===1,'Replay reuses one render loop and AudioContext');
 ok(!Object.values(e.el).some(el=>/\b(?:NaN|Infinity|undefined)\b/.test(el.textContent+' '+el.innerHTML)),'No invalid display values');
 const limited=environment({reduced:true,audioAvailable:false,storageFail:true});await limited.advance(100);limited.el.connect.fire('click');await limited.tap();limited.pointer('pointerdown');await limited.advance(1100);limited.pointer('pointerup');await limited.advance(61000,1000);ok(!limited.el.result.hidden&&limited.vibrations.length===0,'Missing storage/audio and reduced motion still finish a run');limited.el.reconnect.fire('click');ok(limited.el.result.hidden,'Storage failure never blocks replay');
 const corrupt=environment({stored:'{"sync":"bad","rank":"INVALID"}'});corrupt.el.connect.fire('click');await corrupt.advance(61000,1000);ok(!corrupt.el.result.hidden,'Corrupt localStorage safely ignored');
 const edge=environment({audioAvailable:false});edge.el.connect.fire('click');await edge.advance(59750,1000);await edge.tap();await edge.advance(1000,1000);ok(!edge.el.result.hidden&&Number(edge.el.resultSync.textContent)>0,'Final valid tap scores even if double-tap window crosses 60 seconds');
 console.log(`${passed} behavioral checks passed. Browser/device checks remain separate.`);
}
run().catch(error=>{console.error(error);process.exitCode=1;});
