#!/usr/bin/env node
'use strict';
// Runs the shipped script with minimal browser fakes; this does not test rendering,
// real sound, browser gesture policy, touch hardware, or actual performance.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const script=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');
function environment({reduced=false,audioAvailable=true}={}){
 let now=1000,serial=0,drawCalls=0;const rafs=new Map(),timers=new Map(),audioContexts=[],vibrations=[];
 class Events{constructor(){this.listeners={};}addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}removeEventListener(type,fn){this.listeners[type]=(this.listeners[type]||[]).filter(f=>f!==fn);}fire(type,fields={}){const e={type,target:this,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;},...fields};for(const fn of this.listeners[type]||[])fn(e);return e;}}
 class Classes{constructor(v=''){this.values=new Set(v.split(/\s+/).filter(Boolean));}add(v){this.values.add(v);}remove(v){this.values.delete(v);}contains(v){return this.values.has(v);}toggle(v,on){if(on===undefined)on=!this.values.has(v);on?this.add(v):this.remove(v);return on;}}
 const draw=new Proxy({createRadialGradient(){return{addColorStop(){}};}},{get(target,key){if(key in target)return target[key];return(...args)=>{drawCalls++;for(const value of args)if(typeof value==='number')assert.ok(Number.isFinite(value),`Canvas ${String(key)} received ${value}`);if(key==='arc')assert.ok(args[2]>=0,'Canvas arc radius must be nonnegative');};},set(target,key,value){target[key]=value;return true;}});
 class Element extends Events{constructor(tag='div',attrs=''){super();this.tagName=tag.toUpperCase();this.attributes={};for(const m of attrs.matchAll(/([\w-]+)\s*=\s*["']([^"']*)["']/g))this.attributes[m[1]]=m[2];this.id=this.attributes.id||'';this.hidden=/\bhidden(?:\s|>|$)/.test(attrs);this.classList=new Classes(this.attributes.class);this.style={setProperty(name,value){this[name]=value;}};this.textContent='';this.innerHTML='';this.captures=new Set();this.width=300;this.height=150;}getContext(){return draw;}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]??null;}getBoundingClientRect(){return this.id==='stage'?{left:22,top:64,width:346,height:548}:{left:0,top:0,width:390,height:844};}setPointerCapture(id){this.captures.add(id);}hasPointerCapture(id){return this.captures.has(id);}releasePointerCapture(id){this.captures.delete(id);}closest(){return['BUTTON','INPUT','SELECT','TEXTAREA'].includes(this.tagName)?this:null;}}
 const elements={};for(const m of html.matchAll(/<([a-z][\w-]*)\b([^>]*\bid\s*=\s*["'][^"']+["'][^>]*)>/gi)){const el=new Element(m[1],m[2]);elements[el.id]=el;}
 const doc=new Events();doc.hidden=false;doc.body=new Element('body');doc.getElementById=id=>{assert.ok(elements[id],'Missing element '+id);return elements[id];};doc.createElement=tag=>new Element(tag);
 const win=new Events();const motion=new Events();motion.matches=reduced;motion.addListener=fn=>motion.addEventListener('change',fn);
 const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){},linearRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}});
 const node=()=>({gain:param(),frequency:param(),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),connect(){return this;},disconnect(){},start(){},stop(){}});
 class FakeAudioContext{constructor(){this.state='suspended';this.destination=node();this.resumeCalls=0;this.suspendCalls=0;audioContexts.push(this);}get currentTime(){return now/1000;}createGain(){return node();}createDynamicsCompressor(){return node();}createOscillator(){return node();}resume(){this.resumeCalls++;this.state='running';this.onstatechange?.();return Promise.resolve();}suspend(){this.suspendCalls++;this.state='suspended';this.onstatechange?.();return Promise.resolve();}}
 const timer=(fn,delay,repeat)=>{const id=++serial;timers.set(id,{fn,due:now+(Number(delay)||0),repeat});return id;};
 const globals={console,document:doc,performance:{now:()=>now},navigator:{vibrate:p=>vibrations.push(p)},devicePixelRatio:3,matchMedia:()=>motion,ResizeObserver:class{observe(){}disconnect(){}},requestAnimationFrame:fn=>{const id=++serial;rafs.set(id,fn);return id;},cancelAnimationFrame:id=>rafs.delete(id),setInterval:(fn,ms)=>timer(fn,ms,ms),clearInterval:id=>timers.delete(id),setTimeout:(fn,ms)=>timer(fn,ms,0),clearTimeout:id=>timers.delete(id),addEventListener:win.addEventListener.bind(win),removeEventListener:win.removeEventListener.bind(win)};
 if(audioAvailable)globals.AudioContext=FakeAudioContext;globals.window=globals;
 vm.runInNewContext(script,globals,{filename:'index.html',timeout:3000});
 async function advance(ms){const end=now+ms;while(now<end-.001){now=Math.min(end,now+1000/60);for(const [id,task] of [...timers])if(task.due<=now){if(task.repeat)task.due+=task.repeat;else timers.delete(id);task.fn();}const queue=[...rafs];rafs.clear();for(const [,fn]of queue)fn(now);await Promise.resolve();}}
 function pointer(type,extra={}){return elements.stage.fire(type,{pointerId:1,isPrimary:true,button:0,clientX:195,clientY:320,target:elements.coreTarget,...extra});}
 async function tap(extra={}){pointer('pointerdown',extra);await advance(65);pointer('pointerup',extra);await Promise.resolve();}
 return{el:elements,win,doc,advance,pointer,tap,audioContexts,vibrations,rafCount:()=>rafs.size,timerCount:()=>timers.size,drawCalls:()=>drawCalls};
}
let passed=0;function ok(condition,message){assert.ok(condition,message);passed++;console.log('PASS '+message);}
async function run(){
 const e=environment();await e.advance(300);ok(e.audioContexts.length===0,'Boot never opens AudioContext');
 e.el.connect.fire('click');await e.advance(50);ok(e.el.connect.hidden&&!e.el.overdrive.hidden&&e.el.linkState.textContent==='LINKED','Connect transitions to interactive controls');ok(e.el.stageMode.textContent==='NEURAL LINK ACTIVE','Connect updates the stage mode immediately');ok(e.audioContexts.length===1&&e.el.sound.getAttribute('aria-pressed')==='true','Gesture enables one audio context and visible sound state');
 const first=Number(e.el.energyValue.textContent);await e.tap();ok(Number(e.el.energyValue.textContent)>first,'Tap raises visible energy');ok(!e.el.stage.hasPointerCapture(1),'Tap releases pointer capture');
 await e.advance(400);e.pointer('pointerdown');await e.advance(1520);ok(e.el.coreStatus.textContent==='RELEASE TO UNLEASH','Long hold reaches visible full-charge state');e.pointer('pointerup',{clientX:410});ok(e.el.eventTitle.textContent==='FULL RESONANCE'&&!e.el.stage.hasPointerCapture(1),'Captured release outside core discharges and releases capture');
 await e.advance(1500);await e.tap();await e.advance(100);await e.tap();ok(e.el.eventTitle.textContent==='N O V A','Nearby double tap triggers NOVA');
 const signal=()=>Number(e.el.feed.innerHTML.match(/signal (\d+)/)?.[1]);await e.advance(110);const n=signal();await e.tap();await e.advance(60);await e.tap();await e.advance(110);ok(signal()===n+1,'NOVA cooldown prevents a repeated burst while normal tap is retained');
 e.el.overdrive.fire('click');ok(e.el.overdrive.getAttribute('aria-pressed')==='true'&&e.el.overdriveLabel.textContent==='STABILIZE','OVERDRIVE exposes the active stabilization control');await e.advance(9250);ok(e.el.overdrive.getAttribute('aria-pressed')==='false'&&e.el.overdriveLabel.textContent==='OVERDRIVE'&&e.el.stageMode.textContent==='NEURAL LINK ACTIVE','OVERDRIVE expires and restores coherent HUD');
 e.pointer('pointerdown');await e.advance(650);e.pointer('pointerdown',{pointerId:2,isPrimary:false});e.pointer('pointercancel',{pointerId:2,isPrimary:false});await e.advance(150);ok(e.el.energyLabel.textContent==='CHARGE / HOLD TO FOCUS'&&e.el.stage.hasPointerCapture(1),'Secondary finger cancellation does not interrupt primary charge');e.pointer('pointerup',{pointerId:2,isPrimary:false});ok(e.el.stage.hasPointerCapture(1),'Secondary release cannot finish primary charge');e.pointer('pointercancel');await e.advance(120);ok(e.el.energyLabel.textContent==='NEURAL ENERGY'&&!e.el.stage.hasPointerCapture(1),'Primary cancellation safely resets charge');
 e.pointer('pointerdown');await e.advance(700);e.pointer('lostpointercapture');await e.advance(120);ok(e.el.energyLabel.textContent==='NEURAL ENERGY','Lost pointer capture resets charge');
 e.el.coreTarget.fire('keydown',{code:'Space',repeat:false});await e.advance(700);e.el.coreTarget.fire('blur');await e.advance(120);ok(e.el.energyLabel.textContent==='NEURAL ENERGY','Keyboard focus loss cannot leave charge stuck');
 e.el.sound.fire('click');await Promise.resolve();await Promise.resolve();ok(e.el.sound.getAttribute('aria-pressed')==='false','Mute updates visible state');await e.tap();ok(e.el.sound.getAttribute('aria-pressed')==='false'&&e.audioContexts[0].state==='suspended','Further taps respect intentional mute');e.el.sound.fire('click');await Promise.resolve();await Promise.resolve();ok(e.el.sound.getAttribute('aria-pressed')==='true','Sound can be enabled again');
 e.doc.hidden=true;e.doc.fire('visibilitychange');const drawn=e.drawCalls();await e.advance(300);ok(e.rafCount()===0&&e.drawCalls()===drawn,'Hidden page stops requesting and drawing frames');ok(e.audioContexts[0].state==='suspended'&&e.timerCount()===0,'Hidden page suspends audio and clock timer');e.doc.hidden=false;e.doc.fire('visibilitychange');await e.advance(150);ok(e.rafCount()===1&&e.drawCalls()>drawn,'Returning visible resumes exactly one render loop');e.el.sound.fire('click');await Promise.resolve();await Promise.resolve();ok(e.el.sound.getAttribute('aria-pressed')==='true'&&e.audioContexts[0].state==='running','One sound-button click restores audio after background suspension');
 e.win.fire('pagehide');ok(e.rafCount()===0&&e.timerCount()===0,'Pagehide clears render and clock work');e.win.fire('pageshow');await e.advance(80);ok(e.rafCount()===1&&e.timerCount()===1,'Pageshow restores one loop and one clock');
 ok(!Object.values(e.el).some(el=>/\b(?:NaN|Infinity|undefined)\b/.test(el.textContent+' '+el.innerHTML)),'Interactions leave no invalid numeric text');
 const limited=environment({reduced:true,audioAvailable:false});await limited.advance(100);limited.el.connect.fire('click');await limited.tap();limited.pointer('pointerdown');await limited.advance(1500);limited.pointer('pointerup');limited.el.overdrive.fire('click');await limited.advance(100);ok(limited.el.overdrive.getAttribute('aria-pressed')==='true'&&limited.vibrations.length===0,'Reduced-motion and missing audio keep core interactions functional without vibration');
 console.log(`\n${passed} behavioral checks passed. Rendering, real audio and hardware remain browser/device checks.`);
}
run().catch(error=>{console.error(error);process.exitCode=1;});
